### ISSUE TITLE
Building the slides

### ISSUE THREAD

**Issue by alexconlin** [Derek-Jones/ESEUR-workshop#1]
I managed to build the slides on my mac - I had a couple of bumps in the road which might be useful for others:

-1. I had to replace the hardcoded directory paths to the paths to the files on my computer. I did that with the following command:

```
perl -p -i -e 's/usr1\/rbook/Users\/MYUSERNAME\/ESEUR-code-data/g' `grep -ril "usr1/rbook" *`
```

-2. I had to install the "source-highlight" package in order to build the slides. I used homebrew like so:

```
brew install source-highlight
```

**Comment by Derek-Jones** [comment]
Thanks Alex.

Completely forgot about source-highlighter.  Have included a less minimal r.lang
